import './globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

const newLocal = Inter({ subsets: ['latin'] })
const inter = newLocal

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" >
        <body className={inter.className} style={{'minHeight':'100vh'}}>{children}</body>
      </html>
    </ClerkProvider>

  )
}
